// Deadlock's shop items, for the "Random Build" challenge. Generated from
// api.deadlock-api.com/v1/assets/items (filtered to shopable, non-deprecated, non-
// Legendary items) - not hand-maintained, re-run the generation script if the item
// roster changes.
//
// "conflictsWith" is the full transitive closure of an item's upgrade family (e.g.
// Mystic Expansion -> Greater Expansion, and Greater Expansion's own further upgrades,
// if any) so a random build never contains two items from the same build chain.

export interface DeadlockItem {
  slug: string
  name: string
  category: 'weapon' | 'vitality' | 'spirit'
  tier: 1 | 2 | 3 | 4
  cost: number
  icon: string
  description: string
  conflictsWith: string[]
}

export const DEADLOCK_ITEMS: DeadlockItem[] = [
  { slug: "extra-charge", name: "Extra Charge", category: "spirit", tier: 1, cost: 800, icon: "/assets/items/extra-charge.webp", description: "", conflictsWith: ["rapid-recharge"] },
  { slug: "extra-spirit", name: "Extra Spirit", category: "spirit", tier: 1, cost: 800, icon: "/assets/items/extra-spirit.webp", description: "", conflictsWith: ["boundless-spirit","improved-spirit","surge-of-power"] },
  { slug: "golden-goose-egg", name: "Golden Goose Egg", category: "spirit", tier: 1, cost: 800, icon: "/assets/items/golden-goose-egg.webp", description: "Gain souls over time, as long as you are alive.", conflictsWith: [] },
  { slug: "mystic-burst", name: "Mystic Burst", category: "spirit", tier: 1, cost: 800, icon: "/assets/items/mystic-burst.webp", description: "Charges up over time with bonus spirit damage, causing abilities dealing more than 80 damage to deal additional damage.", conflictsWith: ["tankbuster"] },
  { slug: "mystic-expansion", name: "Mystic Expansion", category: "spirit", tier: 1, cost: 800, icon: "/assets/items/mystic-expansion.webp", description: "Imbue an ability to increase its range and effect radius.", conflictsWith: ["ballistic-enchantment","greater-expansion"] },
  { slug: "mystic-regeneration", name: "Mystic Regeneration", category: "spirit", tier: 1, cost: 800, icon: "/assets/items/mystic-regeneration.webp", description: "Dealing spirit damage to enemy Heroes grants you Bonus regeneration. Stacks when dealing damage to different heroes.", conflictsWith: ["radiant-regeneration"] },
  { slug: "rusted-barrel", name: "Rusted Barrel", category: "spirit", tier: 1, cost: 800, icon: "/assets/items/rusted-barrel.webp", description: "Target an enemy to reduce their Fire Rate and Bullet Resistance.", conflictsWith: ["disarming-hex"] },
  { slug: "spirit-strike", name: "Spirit Strike", category: "spirit", tier: 1, cost: 800, icon: "/assets/items/spirit-strike.webp", description: "When you perform a Light or Heavy Melee attack against a hero, deal extra spirit damage with the attack and reduce the target's Spirit Resist.Cooldown is 2x longer for Light Melee hits.", conflictsWith: ["spirit-snatch"] },
  { slug: "arcane-surge", name: "Arcane Surge", category: "spirit", tier: 2, cost: 1600, icon: "/assets/items/arcane-surge.webp", description: "After you Dash-Jump, the next ability you use within 7s will have bonus Range, Duration, and Spirit Power.", conflictsWith: ["extra-stamina","kinetic-dash","stamina-mastery"] },
  { slug: "bullet-resist-shredder", name: "Bullet Resist Shredder", category: "spirit", tier: 2, cost: 1600, icon: "/assets/items/bullet-resist-shredder.webp", description: "Reduces Bullet Resist on enemies when you deal spirit damage.", conflictsWith: [] },
  { slug: "cold-front", name: "Cold Front", category: "spirit", tier: 2, cost: 1600, icon: "/assets/items/cold-front.webp", description: "Release an expanding ice blast that deals spirit damage and Slows targets it hits.", conflictsWith: ["arctic-blast"] },
  { slug: "compress-cooldown", name: "Compress Cooldown", category: "spirit", tier: 2, cost: 1600, icon: "/assets/items/compress-cooldown.webp", description: "Imbue an ability to reduce its Cooldown.", conflictsWith: ["superior-cooldown","transcendent-cooldown"] },
  { slug: "duration-extender", name: "Duration Extender", category: "spirit", tier: 2, cost: 1600, icon: "/assets/items/duration-extender.webp", description: "Imbue an ability to increase its Duration.", conflictsWith: ["superior-duration"] },
  { slug: "improved-spirit", name: "Improved Spirit", category: "spirit", tier: 2, cost: 1600, icon: "/assets/items/improved-spirit.webp", description: "", conflictsWith: ["boundless-spirit","extra-spirit","surge-of-power"] },
  { slug: "mystic-slow", name: "Mystic Slow", category: "spirit", tier: 2, cost: 1600, icon: "/assets/items/mystic-slow.webp", description: "When the target takes spirit damage, they have their Move Speed reduced.", conflictsWith: ["lightning-scroll"] },
  { slug: "mystic-vulnerability", name: "Mystic Vulnerability", category: "spirit", tier: 2, cost: 1600, icon: "/assets/items/mystic-vulnerability.webp", description: "When an enemy takes spirit damage, they have their spirit resist reduced.", conflictsWith: ["escalating-exposure"] },
  { slug: "quicksilver-reload", name: "Quicksilver Reload", category: "spirit", tier: 2, cost: 1600, icon: "/assets/items/quicksilver-reload.webp", description: "Your imbued ability charges up over time with bonus spirit damage, bonus fire rate, and reloads bullets on use.", conflictsWith: ["mercurial-magnum"] },
  { slug: "slowing-hex", name: "Slowing Hex", category: "spirit", tier: 2, cost: 1600, icon: "/assets/items/slowing-hex.webp", description: "Slows movement of enemy target. Also Silences their movement-based items and abilities.Increases the target's gravity.Does not affect target's stamina usage.", conflictsWith: ["vortex-web"] },
  { slug: "spirit-sap", name: "Spirit Sap", category: "spirit", tier: 2, cost: 1600, icon: "/assets/items/spirit-sap.webp", description: "Target an enemy to reduce their Spirit Resist and Spirit Power.", conflictsWith: ["focus-lens"] },
  { slug: "suppressor", name: "Suppressor", category: "spirit", tier: 2, cost: 1600, icon: "/assets/items/suppressor.webp", description: "When you deal spirit damage to enemies, you also reduce their Fire Rate.", conflictsWith: [] },
  { slug: "decay", name: "Decay", category: "spirit", tier: 3, cost: 3200, icon: "/assets/items/decay.webp", description: "Inflict damage over time to a target, dealing damage based on their current health.Decay's damage is non-lethal and does not apply item procs.", conflictsWith: [] },
  { slug: "disarming-hex", name: "Disarming Hex", category: "spirit", tier: 3, cost: 3200, icon: "/assets/items/disarming-hex.webp", description: "Disarms enemy target and reduces their Bullet Resist.", conflictsWith: ["rusted-barrel"] },
  { slug: "greater-expansion", name: "Greater Expansion", category: "spirit", tier: 3, cost: 3200, icon: "/assets/items/greater-expansion.webp", description: "Increases the range and effect radius of your abilities and items.", conflictsWith: ["ballistic-enchantment","mystic-expansion"] },
  { slug: "knockdown", name: "Knockdown", category: "spirit", tier: 3, cost: 3200, icon: "/assets/items/knockdown.webp", description: "Apply a Stun after 2s. Stun duration is increased against airborne targets.Increases the target's gravity for the duration of the stun.", conflictsWith: [] },
  { slug: "radiant-regeneration", name: "Radiant Regeneration", category: "spirit", tier: 3, cost: 3200, icon: "/assets/items/radiant-regeneration.webp", description: "Heal and gain bonus Movement Speed for a short duration when you cast an ability.", conflictsWith: ["mystic-regeneration"] },
  { slug: "rapid-recharge", name: "Rapid Recharge", category: "spirit", tier: 3, cost: 3200, icon: "/assets/items/rapid-recharge.webp", description: "", conflictsWith: ["extra-charge"] },
  { slug: "silence-wave", name: "Silence Wave", category: "spirit", tier: 3, cost: 3200, icon: "/assets/items/silence-wave.webp", description: "Launch an expanding projectile which Silences enemies for a short duration and deals impact damage. Silence does not interrupt channeling abilities.", conflictsWith: [] },
  { slug: "spirit-snatch", name: "Spirit Snatch", category: "spirit", tier: 3, cost: 3200, icon: "/assets/items/spirit-snatch.webp", description: "When you perform a Light or Heavy Melee attack against a hero, the attack deals extra spirit damage and steals Spirit Resist and Spirit Power.Effects are reduced by 30% for Light Melee hits.", conflictsWith: ["spirit-strike"] },
  { slug: "superior-cooldown", name: "Superior Cooldown", category: "spirit", tier: 3, cost: 3200, icon: "/assets/items/superior-cooldown.webp", description: "Reduces the Cooldown of your abilities.", conflictsWith: ["compress-cooldown","transcendent-cooldown"] },
  { slug: "superior-duration", name: "Superior Duration", category: "spirit", tier: 3, cost: 3200, icon: "/assets/items/superior-duration.webp", description: "Increases the duration of your abilities and items.", conflictsWith: ["duration-extender"] },
  { slug: "surge-of-power", name: "Surge of Power", category: "spirit", tier: 3, cost: 3200, icon: "/assets/items/surge-of-power.webp", description: "Imbue an ability with permanent Spirit Power. When that ability is used, gain bonus Move Speed and maintain full speed while attacking.", conflictsWith: ["boundless-spirit","extra-spirit","improved-spirit"] },
  { slug: "tankbuster", name: "Tankbuster", category: "spirit", tier: 3, cost: 3200, icon: "/assets/items/tankbuster.webp", description: "Charges up over time with bonus spirit damage, causing abilities dealing more than 165 damage to deal additional damage. Ignores Spirit Resistance.", conflictsWith: ["mystic-burst"] },
  { slug: "torment-pulse", name: "Torment Pulse", category: "spirit", tier: 3, cost: 3200, icon: "/assets/items/torment-pulse.webp", description: "Periodically deals spirit damage to the closest two enemies nearby.", conflictsWith: [] },
  { slug: "arctic-blast", name: "Arctic Blast", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/arctic-blast.webp", description: "Release an expanding ice blast that deals spirit damage, Freezing and then Slowing targets it hits.Slowed targets have their stamina regen frozen", conflictsWith: ["cold-front"] },
  { slug: "boundless-spirit", name: "Boundless Spirit", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/boundless-spirit.webp", description: "", conflictsWith: ["extra-spirit","improved-spirit","surge-of-power"] },
  { slug: "cursed-relic", name: "Cursed Relic", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/cursed-relic.webp", description: "Curses an enemy - interrupting, Silencing, Disarming, and preventing item usage. Removes all non-ultimate buffs.Your own Damage Output is reduced for the duration.", conflictsWith: [] },
  { slug: "echo-shard", name: "Echo Shard", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/echo-shard.webp", description: "", conflictsWith: [] },
  { slug: "escalating-exposure", name: "Escalating Exposure", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/escalating-exposure.webp", description: "Dealing spirit damage applies a stacking Spirit Amp that increases your spirit damage to the target.", conflictsWith: ["mystic-vulnerability"] },
  { slug: "ethereal-shift", name: "Ethereal Shift", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/ethereal-shift.webp", description: "You enter a void state and become untargetable and invincible for a short duration, during which you float slowly and cannot perform actions. Afterwards you gain Spirit Power, Move Speed, and Spirit Resist.Can be canceled early.Activation cancels any active ability.", conflictsWith: [] },
  { slug: "focus-lens", name: "Focus Lens", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/focus-lens.webp", description: "Target an enemy to Silence them. A portion of all damage dealt during the silence gets applied to the target when the silence wears off.", conflictsWith: ["spirit-sap"] },
  { slug: "lightning-scroll", name: "Lightning Scroll", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/lightning-scroll.webp", description: "Damage from your ultimate applies a stun and deals bonus spirit damage after a short delay.", conflictsWith: ["mystic-slow"] },
  { slug: "magic-carpet", name: "Magic Carpet", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/magic-carpet.webp", description: "Summon a Magic Carpet that will fly you away. While flying you are immune to slows and doing any action will dismiss the carpet. Cannot use abilities while the carpet is being summoned.", conflictsWith: [] },
  { slug: "mercurial-magnum", name: "Mercurial Magnum", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/mercurial-magnum.webp", description: "Your imbued ability charges up over time with bonus spirit damage, bonus fire rate, and reloads bullets on use. Until your next reload, your bullets deal bonus spirit damage based on your Spirit Power.", conflictsWith: ["quicksilver-reload"] },
  { slug: "mystic-reverb", name: "Mystic Reverb", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/mystic-reverb.webp", description: "", conflictsWith: [] },
  { slug: "refresher", name: "Refresher", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/refresher.webp", description: "Reset the cooldown of all your abilities and restore all your charges.", conflictsWith: [] },
  { slug: "scourge", name: "Scourge", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/scourge.webp", description: "Apply Spirit Resist, Debuff Resist and an aura on a friendly target that deals damage to enemies proportional to their max health. Existing debuffs on the target are reduced.Can be self cast.", conflictsWith: [] },
  { slug: "spirit-burn", name: "Spirit Burn", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/spirit-burn.webp", description: "Dealing significant spirit damage to an enemy within 5s causes an explosion dealing damage and a burn to that enemy. While burning, enemies take damage over time and receive reduced healing.The cooldown is per enemy, so each target can only be burned once per cooldown. Deals half-damage on non-heroes.", conflictsWith: [] },
  { slug: "transcendent-cooldown", name: "Transcendent Cooldown", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/transcendent-cooldown.webp", description: "Reduces the Cooldown of your abilities and items.", conflictsWith: ["compress-cooldown","superior-cooldown"] },
  { slug: "vortex-web", name: "Vortex Web", category: "spirit", tier: 4, cost: 6400, icon: "/assets/items/vortex-web.webp", description: "", conflictsWith: ["slowing-hex"] },
  { slug: "extra-health", name: "Extra Health", category: "vitality", tier: 1, cost: 800, icon: "/assets/items/extra-health.webp", description: "", conflictsWith: ["colossus","fortitude"] },
  { slug: "extra-regen", name: "Extra Regen", category: "vitality", tier: 1, cost: 800, icon: "/assets/items/extra-regen.webp", description: "", conflictsWith: ["healing-booster","healing-tempo"] },
  { slug: "extra-stamina", name: "Extra Stamina", category: "vitality", tier: 1, cost: 800, icon: "/assets/items/extra-stamina.webp", description: "", conflictsWith: ["arcane-surge","kinetic-dash","stamina-mastery"] },
  { slug: "grit", name: "Grit", category: "vitality", tier: 1, cost: 800, icon: "/assets/items/grit.webp", description: "Gain a Barrier for a short duration.", conflictsWith: ["divine-barrier","guardian-ward","indomitable","reactive-barrier","spirit-shielding","weapon-shielding"] },
  { slug: "healing-rite", name: "Healing Rite", category: "vitality", tier: 1, cost: 800, icon: "/assets/items/healing-rite.webp", description: "Grant Regen and Sprint Speed to the target. Gets dispelled if you take damage from enemy players or objectives. Can be self-cast.", conflictsWith: ["healing-nova","rescue-beam"] },
  { slug: "melee-lifesteal", name: "Melee Lifesteal", category: "vitality", tier: 1, cost: 800, icon: "/assets/items/melee-lifesteal.webp", description: "Your next Melee attack heals you. This heal is 30% effective vs non-heroes. Cooldown is 1.5x as long for Light Melee hits.", conflictsWith: ["lifestrike"] },
  { slug: "rebuttal", name: "Rebuttal", category: "vitality", tier: 1, cost: 800, icon: "/assets/items/rebuttal.webp", description: "On a successful Parry against an enemy Hero, Heal yourself for the damage parried and returns that damage to the target, and temporarily gain increased damage.", conflictsWith: [] },
  { slug: "sprint-boots", name: "Sprint Boots", category: "vitality", tier: 1, cost: 800, icon: "/assets/items/sprint-boots.webp", description: "", conflictsWith: ["enduring-speed","juggernaut","trophy-collector","veil-walker"] },
  { slug: "battle-vest", name: "Battle Vest", category: "vitality", tier: 2, cost: 1600, icon: "/assets/items/battle-vest.webp", description: "While you are above 65% health, gain weapon damage and bonus fire rate.", conflictsWith: [] },
  { slug: "bullet-lifesteal", name: "Bullet Lifesteal", category: "vitality", tier: 2, cost: 1600, icon: "/assets/items/bullet-lifesteal.webp", description: "", conflictsWith: ["fury-trance","infuser","leech","spirit-lifesteal","spiritual-overflow","vampiric-burst"] },
  { slug: "debuff-reducer", name: "Debuff Reducer", category: "vitality", tier: 2, cost: 1600, icon: "/assets/items/debuff-reducer.webp", description: "Reduces the duration of all negative effects applied to you.", conflictsWith: ["spellbreaker","unstoppable"] },
  { slug: "enchanter-s-emblem", name: "Enchanter's Emblem", category: "vitality", tier: 2, cost: 1600, icon: "/assets/items/enchanter-s-emblem.webp", description: "While you are above 65% health, gain bonus Spirit and Cooldown Reduction.", conflictsWith: [] },
  { slug: "enduring-speed", name: "Enduring Speed", category: "vitality", tier: 2, cost: 1600, icon: "/assets/items/enduring-speed.webp", description: "Reduces the effect of enemy Move Speed penalties.", conflictsWith: ["juggernaut","sprint-boots","trophy-collector","veil-walker"] },
  { slug: "guardian-ward", name: "Guardian Ward", category: "vitality", tier: 2, cost: 1600, icon: "/assets/items/guardian-ward.webp", description: "Provide the target with a Barrier and temporary Move Speed. Can be self-cast.Cooldown is reduced by half when cast on someone else.", conflictsWith: ["divine-barrier","grit","indomitable","reactive-barrier","spirit-shielding","weapon-shielding"] },
  { slug: "healbane", name: "Healbane", category: "vitality", tier: 2, cost: 1600, icon: "/assets/items/healbane.webp", description: "Your spirit damage applies Healing Reduction. If an enemy hero dies under this effect, you receive a large heal.", conflictsWith: [] },
  { slug: "healing-booster", name: "Healing Booster", category: "vitality", tier: 2, cost: 1600, icon: "/assets/items/healing-booster.webp", description: "Increases the effectiveness of your healing.", conflictsWith: ["extra-regen","healing-tempo"] },
  { slug: "reactive-barrier", name: "Reactive Barrier", category: "vitality", tier: 2, cost: 1600, icon: "/assets/items/reactive-barrier.webp", description: "Gain a Barrier when you are Stunned, Chained, Immobilized, Slept or Silenced.", conflictsWith: ["divine-barrier","grit","guardian-ward","indomitable","spirit-shielding","weapon-shielding"] },
  { slug: "restorative-locket", name: "Restorative Locket", category: "vitality", tier: 2, cost: 1600, icon: "/assets/items/restorative-locket.webp", description: "", conflictsWith: [] },
  { slug: "return-fire", name: "Return Fire", category: "vitality", tier: 2, cost: 1600, icon: "/assets/items/return-fire.webp", description: "Automatically fire a bullet towards any attacker who damages you with their abilities or weapon.", conflictsWith: [] },
  { slug: "spirit-lifesteal", name: "Spirit Lifesteal", category: "vitality", tier: 2, cost: 1600, icon: "/assets/items/spirit-lifesteal.webp", description: "", conflictsWith: ["bullet-lifesteal","fury-trance","infuser","leech","spiritual-overflow","vampiric-burst"] },
  { slug: "spirit-shielding", name: "Spirit Shielding", category: "vitality", tier: 2, cost: 1600, icon: "/assets/items/spirit-shielding.webp", description: "Gain a Barrier whenever you take significant spirit damage from enemy Heroes in a small time frame.", conflictsWith: ["divine-barrier","grit","guardian-ward","indomitable","reactive-barrier","weapon-shielding"] },
  { slug: "trophy-collector", name: "Trophy Collector", category: "vitality", tier: 2, cost: 1600, icon: "/assets/items/trophy-collector.webp", description: "Whenever you score an assist or kill, gain extra sprint, ability range and passive soul generation. This effect stacks and persists through death.", conflictsWith: ["enduring-speed","juggernaut","sprint-boots","veil-walker"] },
  { slug: "weapon-shielding", name: "Weapon Shielding", category: "vitality", tier: 2, cost: 1600, icon: "/assets/items/weapon-shielding.webp", description: "Gain a Barrier whenever you take significant weapon damage from enemy Heroes in a small time frame.", conflictsWith: ["divine-barrier","grit","guardian-ward","indomitable","reactive-barrier","spirit-shielding"] },
  { slug: "bullet-resilience", name: "Bullet Resilience", category: "vitality", tier: 3, cost: 3200, icon: "/assets/items/bullet-resilience.webp", description: "When below 50% health, gain additional Bullet Resist.", conflictsWith: [] },
  { slug: "counterspell", name: "Counterspell", category: "vitality", tier: 3, cost: 3200, icon: "/assets/items/counterspell.webp", description: "Your next parry protects you from the damage and effects of enemy abilities and items. On a successful spell parry heal and gain move speed and Spirit.", conflictsWith: [] },
  { slug: "dispel-magic", name: "Dispel Magic", category: "vitality", tier: 3, cost: 3200, icon: "/assets/items/dispel-magic.webp", description: "", conflictsWith: [] },
  { slug: "fortitude", name: "Fortitude", category: "vitality", tier: 3, cost: 3200, icon: "/assets/items/fortitude.webp", description: "After not taking damage for a period, gain health regen.", conflictsWith: ["colossus","extra-health"] },
  { slug: "fury-trance", name: "Fury Trance", category: "vitality", tier: 3, cost: 3200, icon: "/assets/items/fury-trance.webp", description: "", conflictsWith: ["bullet-lifesteal","infuser","leech","spirit-lifesteal","spiritual-overflow","vampiric-burst"] },
  { slug: "healing-nova", name: "Healing Nova", category: "vitality", tier: 3, cost: 3200, icon: "/assets/items/healing-nova.webp", description: "Heal yourself and nearby allies.", conflictsWith: ["healing-rite","rescue-beam"] },
  { slug: "lifestrike", name: "Lifestrike", category: "vitality", tier: 3, cost: 3200, icon: "/assets/items/lifestrike.webp", description: "Your Melee Attack applies Movement Slow and heals you for a percentage of the Melee Damage dealt plus a fixed amount. This heal is 40% effective vs non-heroes. Cooldown is 1.5x as long for Light Melee hits.", conflictsWith: ["melee-lifesteal"] },
  { slug: "majestic-leap", name: "Majestic Leap", category: "vitality", tier: 3, cost: 3200, icon: "/assets/items/majestic-leap.webp", description: "Launch yourself high into the air and grant yourself a Barrier. While in the air, you can use the active again to drop down faster.Cannot be used for 5s if attacked by enemy Hero.", conflictsWith: [] },
  { slug: "metal-skin", name: "Metal Skin", category: "vitality", tier: 3, cost: 3200, icon: "/assets/items/metal-skin.webp", description: "Become immune to bullets.", conflictsWith: [] },
  { slug: "rescue-beam", name: "Rescue Beam", category: "vitality", tier: 3, cost: 3200, icon: "/assets/items/rescue-beam.webp", description: "Heals a target allied hero and yourself for a percentage of Max Health. Once while healing, you can Pull the target towards you. Can be self-cast.", conflictsWith: ["healing-nova","healing-rite"] },
  { slug: "spirit-resilience", name: "Spirit Resilience", category: "vitality", tier: 3, cost: 3200, icon: "/assets/items/spirit-resilience.webp", description: "When below 50% health, gain additional Spirit Resist.", conflictsWith: [] },
  { slug: "stamina-mastery", name: "Stamina Mastery", category: "vitality", tier: 3, cost: 3200, icon: "/assets/items/stamina-mastery.webp", description: "", conflictsWith: ["arcane-surge","extra-stamina","kinetic-dash"] },
  { slug: "veil-walker", name: "Veil Walker", category: "vitality", tier: 3, cost: 3200, icon: "/assets/items/veil-walker.webp", description: "Walking through a cosmic veil grants you Stealth, Heal and increased Move Speed.", conflictsWith: ["enduring-speed","juggernaut","sprint-boots","trophy-collector"] },
  { slug: "warp-stone", name: "Warp Stone", category: "vitality", tier: 3, cost: 3200, icon: "/assets/items/warp-stone.webp", description: "Teleport straight ahead, gaining Bullet Resist.", conflictsWith: [] },
  { slug: "cheat-death", name: "Cheat Death", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/cheat-death.webp", description: "", conflictsWith: [] },
  { slug: "colossus", name: "Colossus", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/colossus.webp", description: "Grow larger in size, gaining bullet resist, spirit resist, and melee damage. Nearby enemies suffer from slow and have reduced dash speed.", conflictsWith: ["extra-health","fortitude"] },
  { slug: "divine-barrier", name: "Divine Barrier", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/divine-barrier.webp", description: "Remove all non-stun debuffs from the target and provide them with a Barrier and Move Speed. Can be self-cast. Cooldown is reduced by half when cast on someone else.", conflictsWith: ["grit","guardian-ward","indomitable","reactive-barrier","spirit-shielding","weapon-shielding"] },
  { slug: "diviner-s-kevlar", name: "Diviner's Kevlar", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/diviner-s-kevlar.webp", description: "Upon casting an ultimate ability gain a Barrier and temporary Spirit Power.", conflictsWith: [] },
  { slug: "healing-tempo", name: "Healing Tempo", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/healing-tempo.webp", description: "Applying heal to yourself or an ally grants the target bonus fire rate and bonus move speed.Does not apply on innate Regen or passive Bullet/Spirit Lifesteals.", conflictsWith: ["extra-regen","healing-booster"] },
  { slug: "indomitable", name: "Indomitable", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/indomitable.webp", description: "", conflictsWith: ["divine-barrier","grit","guardian-ward","reactive-barrier","spirit-shielding","weapon-shielding"] },
  { slug: "infuser", name: "Infuser", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/infuser.webp", description: "Gain Spirit Lifesteal and Spirit Power.", conflictsWith: ["bullet-lifesteal","fury-trance","leech","spirit-lifesteal","spiritual-overflow","vampiric-burst"] },
  { slug: "inhibitor", name: "Inhibitor", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/inhibitor.webp", description: "Your bullets build up to reduce the target's outgoing damage and apply healing reduction.", conflictsWith: [] },
  { slug: "juggernaut", name: "Juggernaut", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/juggernaut.webp", description: "", conflictsWith: ["enduring-speed","sprint-boots","trophy-collector","veil-walker"] },
  { slug: "leech", name: "Leech", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/leech.webp", description: "Reduces the effect of enemy applied healing reduction.", conflictsWith: ["bullet-lifesteal","fury-trance","infuser","spirit-lifesteal","spiritual-overflow","vampiric-burst"] },
  { slug: "phantom-strike", name: "Phantom Strike", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/phantom-strike.webp", description: "Teleport to an enemy target and pull them to the ground. Dealing damage, Move speed reduction and Disarm.", conflictsWith: [] },
  { slug: "plated-armor", name: "Plated Armor", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/plated-armor.webp", description: "Gain a chance to either deflect incoming bullets, preventing all weapon damage or prevent all on-hit effects from bullets.", conflictsWith: [] },
  { slug: "siphon-bullets", name: "Siphon Bullets", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/siphon-bullets.webp", description: "", conflictsWith: [] },
  { slug: "spellbreaker", name: "Spellbreaker", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/spellbreaker.webp", description: "The next instance of high spirit damage you take is significantly reduced.", conflictsWith: ["debuff-reducer","unstoppable"] },
  { slug: "unstoppable", name: "Unstoppable", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/unstoppable.webp", description: "Temporarily suppress negative status effects and become immune to Stun, Silence, Sleep, Root, and Disarm. Cannot be used while Stunned or Slept.", conflictsWith: ["debuff-reducer","spellbreaker"] },
  { slug: "vampiric-burst", name: "Vampiric Burst", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/vampiric-burst.webp", description: "", conflictsWith: ["bullet-lifesteal","fury-trance","infuser","leech","spirit-lifesteal","spiritual-overflow"] },
  { slug: "witchmail", name: "Witchmail", category: "vitality", tier: 4, cost: 6400, icon: "/assets/items/witchmail.webp", description: "Taking heavy hits of spirit damage from an enemy reduces a random ability cooldown.", conflictsWith: [] },
  { slug: "close-quarters", name: "Close Quarters", category: "weapon", tier: 1, cost: 800, icon: "/assets/items/close-quarters.webp", description: "Deal additional Weapon Damage when in close range to your target.", conflictsWith: ["point-blank"] },
  { slug: "extended-magazine", name: "Extended Magazine", category: "weapon", tier: 1, cost: 800, icon: "/assets/items/extended-magazine.webp", description: "", conflictsWith: ["escalating-resilience","titanic-magazine"] },
  { slug: "headshot-booster", name: "Headshot Booster", category: "weapon", tier: 1, cost: 800, icon: "/assets/items/headshot-booster.webp", description: "Your next headshot against an enemy Hero deals bonus weapon damage.", conflictsWith: ["headhunter"] },
  { slug: "high-velocity-rounds", name: "High-Velocity Rounds", category: "weapon", tier: 1, cost: 800, icon: "/assets/items/high-velocity-rounds.webp", description: "", conflictsWith: ["armor-piercing-rounds","express-shot","long-range","opening-rounds","sharpshooter"] },
  { slug: "monster-rounds", name: "Monster Rounds", category: "weapon", tier: 1, cost: 800, icon: "/assets/items/monster-rounds.webp", description: "", conflictsWith: ["cultist-sacrifice"] },
  { slug: "rapid-rounds", name: "Rapid Rounds", category: "weapon", tier: 1, cost: 800, icon: "/assets/items/rapid-rounds.webp", description: "", conflictsWith: ["burst-fire","swift-striker"] },
  { slug: "restorative-shot", name: "Restorative Shot", category: "weapon", tier: 1, cost: 800, icon: "/assets/items/restorative-shot.webp", description: "Your next bullet will heal you based on what target you hit.", conflictsWith: [] },
  { slug: "active-reload", name: "Active Reload", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/active-reload.webp", description: "While reloading, pressing Reload during the highlighted portion will instantly finish your reload and grant you Fire Rate, Bullet Lifesteal and Move Speed.", conflictsWith: [] },
  { slug: "fleetfoot", name: "Fleetfoot", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/fleetfoot.webp", description: "", conflictsWith: [] },
  { slug: "intensifying-magazine", name: "Intensifying Magazine", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/intensifying-magazine.webp", description: "Increases Weapon Damage as you continuously fire your weapon.", conflictsWith: [] },
  { slug: "kinetic-dash", name: "Kinetic Dash", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/kinetic-dash.webp", description: "When you Dash-Jump you gain Fire Rate and bonus Ammo until your next reload. Lasts up to 7s.", conflictsWith: ["arcane-surge","extra-stamina","stamina-mastery"] },
  { slug: "long-range", name: "Long Range", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/long-range.webp", description: "Deal additional Weapon Damage when beyond a minimum distance from your target.", conflictsWith: ["armor-piercing-rounds","express-shot","high-velocity-rounds","opening-rounds","sharpshooter"] },
  { slug: "melee-charge", name: "Melee Charge", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/melee-charge.webp", description: "Your next Heavy Melee attack against an enemy deals increased damage.", conflictsWith: ["crushing-fists"] },
  { slug: "mystic-shot", name: "Mystic Shot", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/mystic-shot.webp", description: "Your next bullet deals bonus spirit damage.", conflictsWith: [] },
  { slug: "opening-rounds", name: "Opening Rounds", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/opening-rounds.webp", description: "Your attacks have additional Weapon Damage against enemies above 50% health.", conflictsWith: ["armor-piercing-rounds","express-shot","high-velocity-rounds","long-range","sharpshooter"] },
  { slug: "recharging-rush", name: "Recharging Rush", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/recharging-rush.webp", description: "Dealing significant weapon damage replenishes a charge for each of your charged abilities.", conflictsWith: [] },
  { slug: "slowing-bullets", name: "Slowing Bullets", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/slowing-bullets.webp", description: "Your bullets build up a Movement Slow on enemies.", conflictsWith: ["weighted-shots"] },
  { slug: "spirit-shredder-bullets", name: "Spirit Shredder Bullets", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/spirit-shredder-bullets.webp", description: "Your bullets apply a debuff that reduces the Spirit Resist of the target and grants you and your allies Spirit Lifesteal against them.", conflictsWith: ["spirit-rend"] },
  { slug: "split-shot", name: "Split Shot", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/split-shot.webp", description: "Make your weapon fire multishot. Hitting more than one Hero per attack will grant a stacking weapon damage bonus. Targets can only be hit once per multishot.", conflictsWith: [] },
  { slug: "stalker", name: "Stalker", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/stalker.webp", description: "Dealing weapon damage at close range opens a wound and grants you bonus move speed. Wounded enemies take spirit damage over time, have reduced bullet resist, and are revealed through walls.", conflictsWith: [] },
  { slug: "swift-striker", name: "Swift Striker", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/swift-striker.webp", description: "", conflictsWith: ["burst-fire","rapid-rounds"] },
  { slug: "titanic-magazine", name: "Titanic Magazine", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/titanic-magazine.webp", description: "", conflictsWith: ["escalating-resilience","extended-magazine"] },
  { slug: "weakening-headshot", name: "Weakening Headshot", category: "weapon", tier: 2, cost: 1600, icon: "/assets/items/weakening-headshot.webp", description: "Landing a Headshot reduces their Bullet Resist.", conflictsWith: ["crippling-headshot"] },
  { slug: "alchemical-fire", name: "Alchemical Fire", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/alchemical-fire.webp", description: "Throw a flask that explodes on contact, creating an area that does increasing spirit damage per second and reduces enemy Bullet Resist.50% less effective vs non-heroes.", conflictsWith: [] },
  { slug: "ballistic-enchantment", name: "Ballistic Enchantment", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/ballistic-enchantment.webp", description: "Imbue an ability with increased range. Dealing damage with that ability grants you increased weapon damage per unique hero hit. Has reduced effect on non-heroes.", conflictsWith: ["greater-expansion","mystic-expansion"] },
  { slug: "berserker", name: "Berserker", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/berserker.webp", description: "Your Weapon Damage increases as you take sustained damage.", conflictsWith: [] },
  { slug: "blood-tribute", name: "Blood Tribute", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/blood-tribute.webp", description: "Toggle: Continually sacrifice Health to improve fire rate, Debuff Resistance and Move Speed.", conflictsWith: [] },
  { slug: "burst-fire", name: "Burst Fire", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/burst-fire.webp", description: "Briefly gain Fire Rate and Move Speed when one of your bullets hits an enemy hero.", conflictsWith: ["rapid-rounds","swift-striker"] },
  { slug: "cultist-sacrifice", name: "Cultist Sacrifice", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/cultist-sacrifice.webp", description: "Target an enemy NPC and consume it for 180% Bonus Souls and grants a powerful long lasting buff.", conflictsWith: ["monster-rounds"] },
  { slug: "escalating-resilience", name: "Escalating Resilience", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/escalating-resilience.webp", description: "Grants Bullet Resist when your bullets hit an enemy hero. Each shot can only grant one stack.", conflictsWith: ["extended-magazine","titanic-magazine"] },
  { slug: "express-shot", name: "Express Shot", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/express-shot.webp", description: "Your next attack will fire twice in quick succession with increased damage and velocity. This attack consumes extra ammo.", conflictsWith: ["armor-piercing-rounds","high-velocity-rounds","long-range","opening-rounds","sharpshooter"] },
  { slug: "headhunter", name: "Headhunter", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/headhunter.webp", description: "Your next headshot against an enemy Hero deals bonus weapon damage, heal you, and briefly grants bonus move speed.", conflictsWith: ["headshot-booster"] },
  { slug: "heroic-aura", name: "Heroic Aura", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/heroic-aura.webp", description: "Provides Bullet Resist to nearby friendly units.", conflictsWith: [] },
  { slug: "hollow-point", name: "Hollow Point", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/hollow-point.webp", description: "When you are above 65% health, deal additional Weapon Damage and your bullets reduce enemy Bullet Resist.", conflictsWith: [] },
  { slug: "hunter-s-aura", name: "Hunter's Aura", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/hunter-s-aura.webp", description: "Reduces nearby enemies' Bullet Resist and Fire Rate. If there is only one enemy hero nearby, this effect is doubled.", conflictsWith: [] },
  { slug: "point-blank", name: "Point Blank", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/point-blank.webp", description: "When in close range to your target, gain Weapon Damage and your bullets apply a Movement Slow.", conflictsWith: ["close-quarters"] },
  { slug: "shadow-weave", name: "Shadow Weave", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/shadow-weave.webp", description: "Become Stealthed. Whenever you take damage while Stealthed you get briefly revealed.", conflictsWith: [] },
  { slug: "sharpshooter", name: "Sharpshooter", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/sharpshooter.webp", description: "Deal additional Weapon Damage when beyond a minimum distance from your target.", conflictsWith: ["armor-piercing-rounds","express-shot","high-velocity-rounds","long-range","opening-rounds"] },
  { slug: "spirit-rend", name: "Spirit Rend", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/spirit-rend.webp", description: "", conflictsWith: ["spirit-shredder-bullets"] },
  { slug: "tesla-bullets", name: "Tesla Bullets", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/tesla-bullets.webp", description: "Your bullets have a chance to shock your target. The shock will jump to a nearby enemy.", conflictsWith: ["capacitor"] },
  { slug: "toxic-bullets", name: "Toxic Bullets", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/toxic-bullets.webp", description: "Your bullets build up a Bleed on enemies, causing them to lose a percentage of their Max Health over time. Also applies Healing Reduction on the bleeding target.", conflictsWith: [] },
  { slug: "weighted-shots", name: "Weighted Shots", category: "weapon", tier: 3, cost: 3200, icon: "/assets/items/weighted-shots.webp", description: "Your bullets build up a Movement Slow on enemies.", conflictsWith: ["slowing-bullets"] },
  { slug: "armor-piercing-rounds", name: "Armor Piercing Rounds", category: "weapon", tier: 4, cost: 6400, icon: "/assets/items/armor-piercing-rounds.webp", description: "Your Bullets have a chance to become unavoidable, piercing through enemies and ignoring their Bullet Resistance.", conflictsWith: ["express-shot","high-velocity-rounds","long-range","opening-rounds","sharpshooter"] },
  { slug: "capacitor", name: "Capacitor", category: "weapon", tier: 4, cost: 6400, icon: "/assets/items/capacitor.webp", description: "Launch a projectile that deals damage, applies a strong slow that recovers over time, prevents Stamina usage and Silences their movement-based items and abilities.", conflictsWith: ["tesla-bullets"] },
  { slug: "crippling-headshot", name: "Crippling Headshot", category: "weapon", tier: 4, cost: 6400, icon: "/assets/items/crippling-headshot.webp", description: "Landing a Headshot will reduce their Bullet and Spirit Resist and applies Healing Reduction.", conflictsWith: ["weakening-headshot"] },
  { slug: "crushing-fists", name: "Crushing Fists", category: "weapon", tier: 4, cost: 6400, icon: "/assets/items/crushing-fists.webp", description: "Your melee damage will restore ammo and apply a stacking bullet resist debuff on enemies. Heavy melee applies 2 stacks. If the target reaches max stacks, they will be stunned.", conflictsWith: ["melee-charge"] },
  { slug: "frenzy", name: "Frenzy", category: "weapon", tier: 4, cost: 6400, icon: "/assets/items/frenzy.webp", description: "", conflictsWith: [] },
  { slug: "glass-cannon", name: "Glass Cannon", category: "weapon", tier: 4, cost: 6400, icon: "/assets/items/glass-cannon.webp", description: "Each hero kill grants permanent Fire Rate (up to a max of 8 times). Death results in the loss of 1 stack.", conflictsWith: [] },
  { slug: "lucky-shot", name: "Lucky Shot", category: "weapon", tier: 4, cost: 6400, icon: "/assets/items/lucky-shot.webp", description: "Your bullets have a chance to be empowered, causing them to deal bonus weapon damage on hit.Bonus damage cannot Crit.", conflictsWith: [] },
  { slug: "ricochet", name: "Ricochet", category: "weapon", tier: 4, cost: 6400, icon: "/assets/items/ricochet.webp", description: "Your bullets will ricochet on enemies near your target, applying any bullet procs and dealing a percentage of the original damage.", conflictsWith: [] },
  { slug: "silencer", name: "Silencer", category: "weapon", tier: 4, cost: 6400, icon: "/assets/items/silencer.webp", description: "Your bullets build up to a Silence. Victims are immune to the build up for 10s after silence expires.", conflictsWith: [] },
  { slug: "spellslinger", name: "Spellslinger", category: "weapon", tier: 4, cost: 6400, icon: "/assets/items/spellslinger.webp", description: "While in-combat whenever you cast an ability or item, gain a stacking buff that improves fire rate and reload speed. Each stack refreshes the duration.", conflictsWith: [] },
  { slug: "spiritual-overflow", name: "Spiritual Overflow", category: "weapon", tier: 4, cost: 6400, icon: "/assets/items/spiritual-overflow.webp", description: "Gain bonus Fire Rate, Spirit Power and Spirit Lifesteal by charging up when shooting enemy heroes.", conflictsWith: ["bullet-lifesteal","fury-trance","infuser","leech","spirit-lifesteal","vampiric-burst"] },
]

export const ITEM_BY_SLUG: Record<string, DeadlockItem> = Object.fromEntries(DEADLOCK_ITEMS.map((i) => [i.slug, i]))

// Picks up to `count` items with no two from the same upgrade family. 156 items across
// only ~35 small conflict clusters (max size 7) means reaching 12 is never actually at
// risk of running out, but the loop still degrades gracefully (returns fewer) instead
// of looping forever if that ever changed.
export function rollRandomBuild(count: number = 12): DeadlockItem[] {
  let remaining = DEADLOCK_ITEMS
  const picked: DeadlockItem[] = []
  while (picked.length < count && remaining.length > 0) {
    const idx = Math.floor(Math.random() * remaining.length)
    const chosen = remaining[idx]
    picked.push(chosen)
    const excluded = new Set([chosen.slug, ...chosen.conflictsWith])
    remaining = remaining.filter((item) => !excluded.has(item.slug))
  }
  return picked
}
